// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: pb/blockchain.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a basic transaction (mirrors core.Transaction initially)
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Future fields:
	// bytes sender_pub_key = 2;
	// bytes recipient_addr = 3;
	// uint64 amount = 4;
	// uint64 nonce = 5;
	// bytes signature = 6;
	Hash          []byte `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"` // Store the transaction hash (calculated separately)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_pb_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Represents a block header (mirrors core.BlockHeader)
type BlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PrevBlockHash []byte                 `protobuf:"bytes,2,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`
	MerkleRoot    []byte                 `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Nonce         uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"` // bytes difficulty_target = 7; // Add later if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_pb_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BlockHeader) GetPrevBlockHash() []byte {
	if x != nil {
		return x.PrevBlockHash
	}
	return nil
}

func (x *BlockHeader) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *BlockHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// Represents a block (mirrors core.Block)
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_pb_blockchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// A wrapper message to send different types of payloads over the network
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Block
	//	*Message_Transaction
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pb_blockchain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetBlock() *Block {
	if x != nil {
		if x, ok := x.Payload.(*Message_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *Message) GetTransaction() *Transaction {
	if x != nil {
		if x, ok := x.Payload.(*Message_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Block struct {
	Block *Block `protobuf:"bytes,1,opt,name=block,proto3,oneof"`
}

type Message_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3,oneof"`
}

func (*Message_Block) isMessage_Payload() {}

func (*Message_Transaction) isMessage_Payload() {}

var File_pb_blockchain_proto protoreflect.FileDescriptor

const file_pb_blockchain_proto_rawDesc = "" +
	"\n" +
	"\x13pb/blockchain.proto\x12\x02pb\"5\n" +
	"\vTransaction\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04hash\x18\a \x01(\fR\x04hash\"\xbc\x01\n" +
	"\vBlockHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12&\n" +
	"\x0fprev_block_hash\x18\x02 \x01(\fR\rprevBlockHash\x12\x1f\n" +
	"\vmerkle_root\x18\x03 \x01(\fR\n" +
	"merkleRoot\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\"e\n" +
	"\x05Block\x12'\n" +
	"\x06header\x18\x01 \x01(\v2\x0f.pb.BlockHeaderR\x06header\x123\n" +
	"\ftransactions\x18\x02 \x03(\v2\x0f.pb.TransactionR\ftransactions\"l\n" +
	"\aMessage\x12!\n" +
	"\x05block\x18\x01 \x01(\v2\t.pb.BlockH\x00R\x05block\x123\n" +
	"\vtransaction\x18\x02 \x01(\v2\x0f.pb.TransactionH\x00R\vtransactionB\t\n" +
	"\apayloadB\x12Z\x10go-blockchain/pbb\x06proto3"

var (
	file_pb_blockchain_proto_rawDescOnce sync.Once
	file_pb_blockchain_proto_rawDescData []byte
)

func file_pb_blockchain_proto_rawDescGZIP() []byte {
	file_pb_blockchain_proto_rawDescOnce.Do(func() {
		file_pb_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_blockchain_proto_rawDesc), len(file_pb_blockchain_proto_rawDesc)))
	})
	return file_pb_blockchain_proto_rawDescData
}

var file_pb_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_blockchain_proto_goTypes = []any{
	(*Transaction)(nil), // 0: pb.Transaction
	(*BlockHeader)(nil), // 1: pb.BlockHeader
	(*Block)(nil),       // 2: pb.Block
	(*Message)(nil),     // 3: pb.Message
}
var file_pb_blockchain_proto_depIdxs = []int32{
	1, // 0: pb.Block.header:type_name -> pb.BlockHeader
	0, // 1: pb.Block.transactions:type_name -> pb.Transaction
	2, // 2: pb.Message.block:type_name -> pb.Block
	0, // 3: pb.Message.transaction:type_name -> pb.Transaction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_blockchain_proto_init() }
func file_pb_blockchain_proto_init() {
	if File_pb_blockchain_proto != nil {
		return
	}
	file_pb_blockchain_proto_msgTypes[3].OneofWrappers = []any{
		(*Message_Block)(nil),
		(*Message_Transaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_blockchain_proto_rawDesc), len(file_pb_blockchain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_blockchain_proto_goTypes,
		DependencyIndexes: file_pb_blockchain_proto_depIdxs,
		MessageInfos:      file_pb_blockchain_proto_msgTypes,
	}.Build()
	File_pb_blockchain_proto = out.File
	file_pb_blockchain_proto_goTypes = nil
	file_pb_blockchain_proto_depIdxs = nil
}
